### ISSUE TITLE
Compatibility with other mods or game versions

### ISSUE THREAD

**Issue by PlasmaShift** [The-Balthazar/BrewLAN#31]
I have seen some of these answers on your moddb comments section but I can't remember them and the answers may have changed. I good place to put this would be here on github so if something breaks at sometime you (or a pull request) can update it here.

The biggest mods would be
FAF forged alliance forever
Loud Project 
-- I remember Loud Project was integrating BrewLan or adding it but it was an older BrewLan at the time
-- so 2 questions here 1 - is there a difference with the Loud Project bundled BrewLan 2 - What is the compatibility with the github version of BrewLan with Loud Project

Lesser mods
Black ops

Game versions -- I don't know if this matters
steam
disk

Another thing you should do is edit your moddb BrewLan description and download description to point to here as the one hosted on moddb is quite outdated, or if it is so old git BrewLan from github instead. That way you will point people here less on the from the moddb comments, and debug less issues from an outdated BrewLan:)

**Comment by The-Balthazar** [comment]
Github version of BrewLAN works fine on FAF; vault update coming eventually; probably soon.
LOUD has their own version that they maintain, it's approximately up to date, and has a bunch of differences for various reasons that aren't may say.
The Github version should work with LOUD, although maintaining that isn't a massive priority since they have their own.
As far as I'm aware, BlackOps works with BrewLAN perfectly fine.
It is developped on the Steam version.
The retail disk and GOG versions aren't different enough from the Steam version for their to be any issues.
The ModDB version is old, but doesn't have any specific issues with anything other than FAF.
